# 查看springboot开启了哪些配置
debug: false


oauth:
  paths:
    token: /token
    authorize: /authorize
    confirm: /approve
    check_token: /decode
    token_key: /key

spring:
  profiles:
    active: mysql
  cache:
    type: simple

---
spring:
    redis:
      host: 119.28.75.143
      database: 0
      port: 6379
    session:
      store-type: redis
    h2:
      console:
        enabled: true
    datasource:
          url: "jdbc:h2:file:./test"
          username: sakura
          password: killer
    profiles: dev
server:
  port: 8080
logging:
  level:
    root: debug


---
spring:
  profiles: archive
  redis:
      host: 119.28.75.143
      database: 0
      port: 6379
  session:
    store-type: redis
server:
  port: 8081

---
spring:
    session:
      store-type: hash_map
    datasource:
          url: "jdbc:mysql://localhost:3306/campus_project?characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true"
          username: root
          password: root
    profiles: mysql
    jpa:
      hibernate:
        ddl-auto: update
    http:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
server:
  port: 8080
logging:
  level:
    root: info
    jdbc:
      sqlonly: ERROR
      sqltiming: ERROR
      audit: ERROR
      resultset: ERROR
      connection: ERROR
      resultsettable: ERROR

#    org.springframework.security: DEBUG