# 查看springboot开启了哪些配置
debug: false

spring:
  profiles:
    active: mysql-local
---
spring:
    redis:
      host: 119.28.75.143
      database: 0
      port: 6379
    session:
      store-type: redis
    jpa:
          hibernate:
            ddl-auto: create-drop
    datasource:
          url: "jdbc:h2:file:./test"
          username: sakura
          password: killer
    profiles: dev
server:
  port: 8080
logging:
  level: debug


---
spring:
  profiles: archive
  redis:
      host: 119.28.75.143
      database: 0
      port: 6379
  session:
    store-type: redis
server:
  port: 8081

---
spring:
    redis:
      host: 119.28.75.143
      database: 0
      port: 6379
    session:
      store-type: redis
    jpa:
      hibernate:
        ddl-auto: update
    datasource:
          url: "jdbc:mysql://119.28.75.143:3306/campus_project?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true" #characterEncoding=utf8
          username: root
          password: rc452860
    profiles: mysql

server:
  port: 8080
logging:
  level: debug
---
spring:
    redis:
      host: 119.28.75.143
      database: 0
      port: 6379
    session:
      store-type: redis
    jpa:
      hibernate:
        ddl-auto: update
    datasource:
          url: "jdbc:mysql://localhost:3306/campus_project?useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&createDatabaseIfNotExist=true" #characterEncoding=utf8
          username: root
          password: root
    profiles: mysql-local

server:
  port: 8080
logging:
  level: debug
